### ISSUE TITLE
`-d` option won't work on `add` command

### ISSUE THREAD

**Issue by a-delannoy** [u8slvn/hyperfocus#4]
After installing hyperfocus and running the init command to setup the database, I tried addind a first test task with some details.

I runned the same command I found in the documentation and got the following result :
```
❯ hyf add "Read the great article about Python" -d "https://python-article.com"
Usage: hyf add [OPTIONS] <title>
Try 'hyf add -h' for help.

✘(error) Got unexpected extra argument (https://python-article.com)
```

It seems like the `-d` option is not accepted.

**Comment by u8slvn** [comment]
Sorry, this is a mistake in the readme. You can find the right usage of `-d` or `--details` in the command documentation: https://hyperfocus.readthedocs.io/en/latest/commands/#add

**Comment by u8slvn** [comment]
README example fixed! Thank you!
